---
application:
  name: "recent-activity"
  project: "Readme-Workflows"
  organization: "QoveryCommunity"
routers:
- name: "main-recent-activity"
  routes:
  - application_name: "recent-activity"
    paths:
    - "/*"
